### ISSUE TITLE
cosmoz-page-location should stop notifying if it's ancestor cosmoz-page-route is about to be deactivated

### ISSUE THREAD

**Issue by megheaiulian** [Neovici/cosmoz-page-router#25]
In `_stateChange` cosmoz-page-router add a new route if needed and deactivates the current one after animation finishes. In the interval `cosmoz-page-location` elements should not trigger hash-param changes.

Proposal: 
 * cosmoz-page-location fires a `cosmoz-page-location-attached` event when attached.
 * cosmoz-page-route listens to `cosmoz-page-location-attached` and adds target elements to a `_locations` element.
 * in _stateChange when a cosmoz-page-route is going to be removed call a `_removeLocations` function on it.
 * in `_removeLocations` detach and remove all elements from `_locations` array

**Comment by megheaiulian** [comment]
This no longer makes sense ....

**Comment by cristinecula** [comment]
woo! 3 yo issue! a bit more and it started kindergarten.
