### ISSUE TITLE
Update to 2.x native

### ISSUE THREAD

**Issue by dotpointer** [Neovici/cosmoz-page-router#38]
Refresh this repo to go 2.x:

- [x] Upgrade to Polymer CLI 1.8 (Fixes build error on node 10)
- [x] Delete and regenerate `yarn.lock`, `package-lock.json` (Might fix one or more security alerts)
- [x] Switch to `.nvmrc` (Copy from cosmoz-behaviors)
- [x] Switch to headless browsers on Travis, drop `sudo` requirement, drop `dist: trusty` configuration to run on default
- [x] Drop 1.x testing (`bower_components-1.x/`, `bower-1.x.json`, `--variants` install, `bower.json` variants, `#1 - 2` version mask -> `#^2.x.x` semver
- [x] Add Sauce Labs configuration
- [x] Switch from local Firefox test to Sauce Labs (Fixes current geckodriver issue with FF63)
- [x] Switch to `polymer-2` linting ruleset (`polymer.json`)
- [x] Upgrade to Polymer 2.x native guidelines (class-based elements, drop this.fire(), etc, etc, see https://www.polymer-project.org/2.0/docs/upgrade)

(List is originally from https://github.com/Neovici/paper-autocomplete-chips/issues/28, may need adjustments to fit the component.)

**Comment by dotpointer** [comment]
@nomego Anything left here?

**Comment by nomego** [comment]
Don't think so, good work!
