### ISSUE TITLE
Extra route appended if running in Shadow DOM mode, breaks the router.

### ISSUE THREAD

**Issue by FLamparski** [Neovici/cosmoz-page-router#5]
Using Polymer 1.1.5. I have the following snippet:

```html
        <cosmoz-page-router id="router">
          <cosmoz-page-route path="/" import="_home.html" template-id="home"></cosmoz-page-route>
          <cosmoz-page-route path="/settings" import="_settings.html" template-id="settings"></cosmoz-page-route>
        </cosmoz-page-router>
```

Under "Shady DOM", the live DOM tree is this:

![screenshot from 2015-10-17 22 11 01](https://cloud.githubusercontent.com/assets/912935/10561338/56fffd74-751c-11e5-9543-46946c54a3d7.png)

However, if I instead tell Polymer to use the real shadow DOM, the live tree becomes:

![screenshot from 2015-10-17 22 15 02](https://cloud.githubusercontent.com/assets/912935/10561347/9a6b4654-751c-11e5-97cc-0d3e8f147ca6.png)

Note the third route at the bottom of the router tag. This causes the template `.html` to 404 and routing to break (or presumably a different route would be loaded if /.html did in fact exist and was a valid template).

**Comment by plequang** [comment]
Hi Filip,

Thanks for reporting this issue.

It was caused by some direct DOM manipulation we forgot to migrate to new `Polymer.dom` API.

This is fixed in version 0.1.8

Pascal
